//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int Id { get; set; }
        public string custID { get; set; }
        public string cardName { get; set; }
        public string cardNo { get; set; }
        public string csv { get; set; }
        public string date { get; set; }
        public string amount { get; set; }
    }
}
