//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spdcEntities5 : DbContext
    {
        public spdcEntities5()
            : base("name=spdcEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appoinment> Appoinments { get; set; }
        public virtual DbSet<credit> credits { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<DocAvailable> DocAvailables { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<mobile> mobiles { get; set; }
    }
}
